### ISSUE TITLE
livewire form not working

### ISSUE THREAD

**Issue by AlizHarb** [mcamara/laravel-localization#908] opened 2024-09-15 00:25 UTC
Hello
I'm unable to call any method from the livewire component
```php
<?php

use Illuminate\Support\Facades\Route;
use App\Livewire;

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::prefix(\Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale())
        ->middleware(['localeSessionRedirect', 'localizationRedirect', 'localeViewPath'])
        ->group(function () {

            // Dashboard
            Route::get('/', Livewire\Pages\Dashboard::class)->name('dashboard');

            // Game Routes
            Route::prefix('game')->group(function () {

                // Crimes
                Route::get('/crimes', Livewire\Game\Crimes::class)->name('crimes');

                // Inventory
                Route::get('/inventory', Livewire\Game\Inventory::class)->name('inventory');
            });

            // Livewire Routes
            \Livewire\Livewire::setUpdateRoute(function ($handle) {
                return Route::post('/livewire/update', $handle);
            });
        });
});
```
```php
<form wire:submit.prevent="commit({{ $crime->id }})" class="mt-3">
                            <x-button type="submit" class="w-full py-2 px-4 h-10 text-center flex justify-center space-x-2 items-center" wire:loading.attr="disabled">
                                <span wire:loading.remove>{{ __('Commit') }}</span>
                                <span wire:loading>
                                    {{ __('Committing...') }}
                                </span>
                            </x-button>
                        </form>
```
```php
<?php

namespace App\Livewire\Game;

use Illuminate\Support\Facades\Redirect;
use Livewire\Component;
use Masmerise\Toaster\Toastable;

class Crimes extends Component
{
    use Toastable;

    public function render()
    {
        $location = auth()->user()->character->location;

        return view('game.crimes', compact('location'))
                ->title(__('crimes.title'));
    }

    public function commit(int $crimeId): Redirect
    {
        flash('The crime has been committed.')->success();
        $this->warning('The quantity on hand is critically low.');

        return $this->redirect(route('crimes'));
    }
}
```

**Comment by iwasherefirst2** [comment] 2024-11-30 22:31
Hi there,

Thank you for reaching out! Unfortunately, your issue is currently unclear, and I’m having trouble understanding exactly what the problem is. To help us assist you better, could you please update your question to include:

- The exact code or steps you are using when calling a method on your Livewire component.
- The expected behavior versus the actual behavior.
- Any error messages or exceptions you're encountering.
- Whether this issue occurs only on localized routes or in all cases.
- A minimal reproducible example if possible.

This additional information will allow us to investigate your issue more effectively. For now, I’ll close this issue, but feel free to reopen it with the requested details. Thank you!

**Closed by iwasherefirst2** 2024-11-30 22:31 UTC
