### ISSUE TITLE
useAcceptLanguageHeader + hideDefaultLocaleInURL

### ISSUE THREAD

**Issue by simplenotezy** [mcamara/laravel-localization#305] opened 2016-03-09 17:14 UTC
As stated in the config files:

```
// IMPORTANT - When hideDefaultLocaleInURL is set to true, the unlocalized root is treated as the applications default locale "app.locale".
// Because of this language negotiation using the Accept-Language header will NEVER occur when hideDefaultLocaleInURL is true.
```

It is not possible to have both useAcceptLanguageHeader and hideDefaultLocaleInURL set to true.

But I would really like this option. When people visit the website for the very first time, I would like to show them the language that is the visitors default.

Is there some workaround to accomplish this?

**Comment by canfiax** [comment] 2016-03-09 19:32
I have created this middleware, with a lot of inspiration from: `LaravelLocalizationRedirectFilter` and `LocaleSessionRedirect`. I don't understand why it is disabled when `hideDefaultLocaleInUrl` is true -- but maybe I'll find out?

Upon initial testing it seems to be working just fine. Will report if I notice it breaks anything:

    <?php

    namespace App\Http\Middleware;

    use Closure;

    use Mcamara\LaravelLocalization\LanguageNegotiator;
    use LaravelLocalization;
    use Illuminate\Http\RedirectResponse;

    class Locale
    {

        /**
         * Handle an incoming request.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  \Closure  $next
         * @return mixed
         */
        public function handle($request, Closure $next)
        {

            /**
             * Auto redirect
             */
            
                if(!session('dont_do_locale_redirect', false)) {
                    $negotiator = new LanguageNegotiator(LaravelLocalization::getDefaultLocale(), LaravelLocalization::getSupportedLocales(), $request);
                    $locale = $negotiator->negotiateLanguage();

                    session(['dont_do_locale_redirect' => true]);
                    app('session')->reflash();
                    
                    $redirection = app('laravellocalization')->getLocalizedURL($locale);

                    return new RedirectResponse($redirection, 302, [ 'Vary' => 'Accept-Language' ]);
                }

            
            /**
             * The package need to be initialized, the locale will
             * be available after first method call. If you have
             * async calls in your project, this filter starts the 
             * locale environment before each request.
             */
            
            $locale = \LaravelGettext::getLocale();


            return $next($request);
        }
    }

**Comment by neoighodaro** [comment] 2016-06-13 05:22
@mcamara can you confiirm why the app disables this because its also beyond me

**Comment by neoighodaro** [comment] 2016-06-13 06:01
@canfiax and what if you visit with a prespecified language in the url? Your code does not account for that does it?

**Comment by iwasherefirst2** [comment] 2018-10-15 12:40
Thats a good workaround @simplenotezy but it will redirect you the first time always to the browser language even if you have something like `mydomain.com/fr/` where you do not want auto-redirecting to browser language. This could be easily fixed by simply checking if a valid locale is given in the url.

The problem why you can't use `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`  
in the method `setLocale` from `LaravelLocalization` (its called in your Route group).  here is the problematic line:

```
            // if we reached this point and hideDefaultLocaleInURL is true
            // we have to assume we are routing to a defaultLocale route.
            if ($this->hideDefaultLocaleInURL()) {
                $this->currentLocale = $this->defaultLocale;
            }
            // but if hideDefaultLocaleInURL is false, we have
            // to retrieve it from the browser...
            else {
                $this->currentLocale = $this->getCurrentLocale();
            }
```
The problem is that one cannot tell from the domain `yourdomain.com` by its own, if it is supposed to retrieve the language from the browser or to fall back to default locale.

I think the best way how to make `useAcceptLanguageHeader` and `hideDefaultLocaleInURL` work by default, would be to fix the `simplenotezy` snippet and integrate it in `LocaleSessionRedirect`.

What do you think about this @mcamara ? I could make a PR if you want.

**Comment by mcamara** [comment] 2018-10-15 14:49
@iwasherefirst2 yeah, I think it's a good idea and can be done in a new PR!

Thanks a lot for your help!

**Closed** 2018-10-16 13:51 UTC
