### ISSUE TITLE
getting error when using localization in package

### ISSUE THREAD

**Issue by WimVanDooren** [mcamara/laravel-localization#551] opened 2018-04-25 06:25 UTC
I installed Mcamara\LaravelLocalization following the documentation but I get an error `Call to undefined method Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale()`

The error comes from my routes file inside a package I am developing. If I use it in my main routes file it works perfect. All other routes of my package work if I remove the localized one, only if I add the localized route I get the error.

```php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    Route::get('/{page}', 'FrontPagesController@index');
});
```

I found on stackoverflow that this could be because `locale` in `config/app.php` is not set but in my case it is set to `en`.

Can someone help me?

**Comment by iwasherefirst2** [comment] 2019-10-12 13:07
This sounds like you have added the `LaravelLocalization` provider but composer did not install the package. Did you find the folder `mcamara` in your vendor folder? Which Laravel Version are you using?

**Comment by WimVanDooren** [comment] 2019-10-14 07:55
Hi, 
The folder is present in vendor.
Now I'm on Laravel 5.7

**Comment by iwasherefirst2** [comment] 2019-10-14 19:26
What is the output if you try to reinstall the package with 

    composer require mcamara/laravel-localization

?

**Comment by iwasherefirst2** [comment] 2019-11-16 12:23
Closing this as it seems to be an non reproducible installation issue

**Closed by iwasherefirst2** 2019-11-16 12:23 UTC
Labels: question
