### ISSUE TITLE
I want localeSessionRedirect to redirect to localized path but the locale as the second route param.

### ISSUE THREAD

**Issue by Mrbeyond** [mcamara/laravel-localization#872] opened 2023-06-07 13:15 UTC
**Is your feature request related to a problem? Please describe.**
I need to refactor my laravel app to have dynamic company slug to prefix all the routes. This would serve as identifier for each branch and to segrate users for each branch because the distinct branch slug serves as url for the branches . This is working fine.

The issue now is with the localization, `\Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class` is changing the route url by preeceding the url path with `en` e.g if the path is `/dashbord` it would change it to `en/dashboard` which was the default behaviour but I want the locale to come after the branch slug like `/branch/en/dashboard` rather it's changing it to  `/en/branch/dashboard`.

**Describe the solution you'd like**
 I want to be able change the index or position of the locale redirect on the route param:
 e.g to be able to set the redirect to any of this  `/branch/en/dashboard`, `/branch/dashboard/en` or `/en/branch/dashboard`.

**Describe alternatives you've considered** 
 Nothing yet.

**Additional context**

**Comment by iwasherefirst2** [comment] 2024-12-03 20:36
Thank you for your suggestion!

This feature has already been requested in [#382](https://github.com/mcamara/laravel-localization/issues/382), but currently, it’s not supported by the package. There’s an ongoing discussion in [#921](https://github.com/mcamara/laravel-localization/issues/921), which might pave the way for this functionality in the future.

For now, I’ll close this issue as a duplicate of #382.

Thank you for your understanding!

**Closed as completed by iwasherefirst2** 2024-12-03 20:36 UTC
