### ISSUE TITLE
getDefaultLocale in local/dev different in production

### ISSUE THREAD

**Issue by yassinetrbls** [mcamara/laravel-localization#910] opened 2024-09-26 14:32 UTC
Hello,

I've added on my blade file:

getDefaultLocale: {{ LaravelLocalization::getDefaultLocale() }}
getCurrentLocale: {{ LaravelLocalization::getCurrentLocale() }}
app.locale: {{ Config::get('app.locale') }}
 app.fallback_locale: {{ Config::get('app.fallback_locale') }}

Output local (dev):

getDefaultLocale: fr 
getCurrentLocale: fr
app.locale: fr 
app.fallback_locale: en

Output production:
getDefaultLocale: en-US 
getCurrentLocale: fr
app.locale: fr
app.fallback_locale: en

I don't understand these differences? Configuration file, laravel version, package are the same.

Our routes are inside:
'prefix' => LaravelLocalization::setLocale(),
'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath', 'localize', 'guest']

I've done 

php artisan config:clear
php artisan cache:clear

multiple times. 

We are hosting our production through Laravel Vapor.

Could you help us?

**Comment by ducvu91** [comment] 2024-12-02 04:14
getDefaultLocale it mean get from config => app => locale. it will load in process provider load if any change, after provider load done, nothing else can change. so if different, you can check any else change in provider or put debug step by step.

**Comment by iwasherefirst2** [comment] 2024-12-02 09:11
It seems like you're encountering unexpected behavior. Let me clarify what the functions return and suggest some potential reasons for the discrepancy:

### What the Functions Return

1. **`getDefaultLocale()`**  
   This value is retrieved from `config('app.locale')` in your `config/app.php` file. It directly corresponds to the `locale` setting defined there.

2. **`getCurrentLocale()`**  
   This is determined by the `setLocale()` method, typically called in your `routes.php` or equivalent routing configuration.  
   - If `hideDefaultLocaleInURL` is enabled, `getCurrentLocale()` will return the default locale if no locale segment is present in the URL.  
   - Otherwise, it reflects the locale parsed from the URL segment or the browser's preferences.

---

### Possible Issues

Given your logs, it's puzzling that `getDefaultLocale()` and `config('app.locale')` return different values. Here are a few possibilities:

1. **Customization or Overrides**  
   If you have forked or modified the LaravelLocalization package (e.g., its constructor), this could lead to unintended behavior. Can you confirm if you're using an unaltered version of the package?

2. **Mixed up logs**  
   Could it be that `en-US` is coming from `getCurrentLocale()` rather than `getDefaultLocale()`? This would occur if `setLocale()` interprets the browser settings or URL segment differently.

3. **Version Compatibility**  
   Can you share the versions of Laravel and LaravelLocalization you’re using? Specific versions might handle locales differently, especially if there have been updates or breaking changes.

---

### Suggestions for Debugging

1. Confirm that `config('app.locale')` consistently returns the expected value in various contexts.  
2. Log or dump the value of `getCurrentLocale()` and calls to `setLocale()` to verify how the locale is being determined.  
   Add logs to files in the vendor folder of `LaravelLocalization.php` on production to see if `$this->configRepository->get('app.locale')` is actually different from `config('app.locale')`.  
   Reference: [LaravelLocalization.php#L143](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L143).  
3. If possible, test with a clean LaravelLocalization installation to rule out customizations or configuration issues.

If you can provide more details, such as your LaravelLocalization configuration and the specific steps to reproduce the issue, it will help pinpoint the problem more accurately.

This issue has been open since September without further updates. I'll close it for now to keep the issue tracker focused. If you're still encountering this problem, please feel free to reopen the issue or provide additional details. Thank you for your understanding!

**Closed by iwasherefirst2** 2024-12-02 09:11 UTC
