### ISSUE TITLE
I have a question about the prefix route

### ISSUE THREAD

**Issue by DouglasTR** [mcamara/laravel-localization#590] opened 2018-09-14 18:48 UTC
I need to change the route of
http://url-to-laravel/en/test
for http://url-to-laravel/test/en

Sorry if was dumb question I'm kind of new at laravel.

**Comment by Sebi94nbg** [comment] 2018-09-16 16:04
Hey,
You would like to change from a prefix to a suffix.

This is not supported as far as I know. I've also tried to build such a solution, but at the end I just used the prefix solution.

Any solutions are welcome.

**Comment by iwasherefirst2** [comment] 2019-10-12 12:28
Closing this as its a duplicate of #566

**Closed by iwasherefirst2** 2019-10-12 12:28 UTC
