### ISSUE TITLE
How to translate routes that already have a prefix?

### ISSUE THREAD

**Issue by arquadrado** [mcamara/laravel-localization#469] opened 2017-06-26 14:54 UTC
I have my admin routes set up like this.

```
Route::middleware(['web'])
        ->prefix('admin')
        ->namespace('Wizinteractive\\Cms\\Http\\Controllers')
        ->group(function () {
            Route::get('/dashboard', [
                'as' => 'admin.dashboard',
                'uses' => 'DashboardController@dashboard'
            ]);
});
```

How can localization works in this scenario? I can't wrap a route group in another route group, I tried and it doesn't achieve the proper end. Is there a way to accomplish this or only routes that don't have prefix can use the localization?

**Comment by fpalamour** [comment] 2018-04-30 07:36
Same issue, still no workaround about this ?

**Comment by iwasherefirst2** [comment] 2019-10-28 11:26
Closing this as its a duplicate of #382

**Closed by iwasherefirst2** 2019-10-28 11:26 UTC
