### ISSUE TITLE
Laravel API routers  got 404

### ISSUE THREAD

**Issue by beshoo** [mcamara/laravel-localization#862] opened 2023-03-19 11:16 UTC
- Version of Laravel : 9.X
- Version of the Laravel-localization package
- Which middleware is used in `Route::groups` : 
```
Route::group(['prefix' => LaravelLocalization::setLocale(),
              'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function()
{
```
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`).

```
 'supportedLocales' => [
   
        'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        'ar'          => ['name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],

    ]
```

```

    // If `hideDefaultLocaleInURL` is true, then a url without locale
    // is identical with the same url with default locale.
    // For example, if `en` is default locale, then `/en/about` and `/about`
    // would be identical.
    //
    // If in addition the middleware `LaravelLocalizationRedirectFilter` is active, then
    // every url with default locale is redirected to url without locale.
    // For example, `/en/about` would be redirected to `/about`.
    // It is recommended to use `hideDefaultLocaleInURL` only in
    // combination with the middleware `LaravelLocalizationRedirectFilter`
    // to avoid duplicate content (SEO).
    //
    // If `useAcceptLanguageHeader` is true, then the first time
    // the locale will be determined from browser and redirect to that language.
    // After that, `hideDefaultLocaleInURL` behaves as usual.
    'hideDefaultLocaleInURL' => false,

    // If you want to display the locales in particular order in the language selector you should write the order here.
    //CAUTION: Please consider using the appropriate locale code otherwise it will not work
    //Example: 'localesOrder' => ['es','en'],
    'localesOrder' => [],

    //  If you want to use custom lang url segments like 'at' instead of 'de-AT', you can use the mapping to tallow the LanguageNegotiator to assign the descired locales based on HTTP Accept Language Header. For example you want ot use 'at', so map HTTP Accept Language Header 'de-AT' to 'at' (['de-AT' => 'at']).
    'localesMapping' => [],

    // Locale suffix for LC_TIME and LC_MONETARY
    // Defaults to most common ".UTF-8". Set to blank on Windows systems, change to ".utf8" on CentOS and similar.
    'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8'),

    // URLs which should not be processed, e.g. '/nova', '/nova/*', '/nova-api/*' or specific application URLs
    // Defaults to []
    'urlsIgnored' => ['/skipped'],

    'httpMethodsIgnored' => ['POST', 'PUT', 'PATCH', 'DELETE'],
```

My Router **api.php**

```

Route::group(['prefix' => LaravelLocalization::setLocale(),
              'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function()
{
        Route::get('/cv/{cv_slug}', [CvsController::class, 'ViewCv']);
});
```

I opened
http://127.0.0.1/cv/api/22333
it redirects me to 
http://127.0.0.1/cv/en/api/22333
with Router not found

I checked 
https://github.com/mcamara/laravel-localization/issues/382
and
https://github.com/mcamara/laravel-localization/issues/482

and I can not make it works!

**Comment by MQady** [comment] 2023-03-19 13:07
I have exactly the same issue

**Comment by GergoKormoczy** [comment] 2023-03-29 14:31
+1...

**Comment by GergoKormoczy** [comment] 2023-03-29 15:17
I don't know if this is the best solution but it is working my case. You should add exception something like this:

`'urlsIgnored' => ['/api/*'],`

config/laravellocalization.php

**Comment by beshoo** [comment] 2023-03-29 15:19
I already set that....
This plugin is not working.....

**Comment by GergoKormoczy** [comment] 2023-03-29 15:22
Then you should run after of course.

```
php artisan optimize:clear
php artisan route:trans:clear
```

**Comment by iwasherefirst2** [comment] 2024-12-04 21:40
API routes should not use the middleware provided by the LaravelLocalization package, as it is intended for web routes. This middleware handles tasks like redirecting users to locale-specific URLs and using sessions or cookies to persist locale information, which are not typically relevant for API routes.

Since this seems unrelated to the package's intended functionality, I will close this issue. If you believe this is still a problem, feel free to reopen it with a clear explanation of the routes and behavior you’re experiencing.

**Closed by iwasherefirst2** 2024-12-04 21:40 UTC

**Comment by beshoo** [comment] 2024-12-04 21:58
> API routes should not use the middleware provided by the LaravelLocalization package, as it is intended for web routes. This middleware handles tasks like redirecting users to locale-specific URLs and using sessions or cookies to persist locale information, which are not typically relevant for API routes.
> 
> Since this seems unrelated to the package's intended functionality, I will close this issue. If you believe this is still a problem, feel free to reopen it with a clear explanation of the routes and behavior you’re experiencing.

Bad Reply ,unfortunately ....

**Comment by iwasherefirst2** [comment] 2024-12-06 22:01
@beshoo  Thank you for raising this issue! Could you create a repository with a fresh Laravel application and a minimal set of routes that demonstrates the problem? This would help us better understand what’s happening.

From the routes.php example you provided, the URL http://127.0.0.1/cv/api/22333 should typically redirect to http://127.0.0.1/en/cv/api/22333. I’m unclear how the URL http://127.0.0.1/cv/en/api/22333 is being generated. If that’s indeed the case, it might indicate a true bug.

If you can provide a reproducible example, please feel free to reopen this issue so we can investigate further. Looking forward to your feedback!
