### ISSUE TITLE
How do i add an Additional Prefix in Url before locale(en,ar,fr)

### ISSUE THREAD

**Issue by AbdulBasit510** [mcamara/laravel-localization#566] opened 2018-07-12 12:30 UTC
I want to add one more dynamic prefix to URL with locales , as locales are rendering automatically working fine , For example 
http://localhost:8000/en/userInfo  with locale language as english ,
http://localhost:8000/fr/userInfo  with locale language as french,

what i want to achieve is Admin as an additional prefix parameter
http://localhost:8000/Admin/en/userInfo  with locale language as english ,
http://localhost:8000/Admin/fr/userInfo  with locale language as french,
OR
what i want to achieve is Guest as an additional prefix parameter
http://localhost:8000/Guest/en/userInfo  with locale language as english ,
http://localhost:8000/Guest/fr/userInfo  with locale language as french,

Any Help Will Be Highly Appreciated as i am stuck from many days in this particular module

**Comment by iwasherefirst2** [comment] 2019-10-12 12:39
This is currently not possible. One would have to changed quite a lot of the package to add such a feature. The holy rule that the language is the first parameter of the url is hardcoded in the LaravelLocalization model, in the redirect middleware and in the caching functionality. One would basically need to rewrite every model, middleware, trait and many tests in order to archive that.

Also, from a SEO perspective, its it recommended to have the locale as first parameter in the url: https://support.google.com/webmasters/answer/182192

**Comment by iwasherefirst2** [comment] 2019-10-19 22:55
Closing this as its a duplicate of #382

**Closed by iwasherefirst2** 2019-10-19 22:55 UTC
Labels: enhancement
