### ISSUE TITLE
localesOrder is being ignored. Always chooses English as default

### ISSUE THREAD

**Issue by RasmusStougaard** [mcamara/laravel-localization#411] opened 2017-02-22 13:53 UTC
I'm using the 1.2.3 package and no matter what i do it changes the default language to english.

The laravellocalization file:

'localesOrder' => ['da', 'en'],

The app config file:

'locale' => 'da',
'fallback_locale' => 'da',

But when i access the site like this:
www.webpage.com

it always changes it to www.webpage.com/en

it should change it to www.webpage.com/da

What am i doing wrong?

**Comment by qerim** [comment] 2017-02-27 07:43
+1

**Comment by RasmusStougaard** [comment] 2017-02-28 09:59
For those reading this and having the same problem, an obvious temp. fix for this would be something like this:

`   Route::get('/', function () {
        return redirect('/da');
    });`

**Comment by sarotnem** [comment] 2017-02-28 14:00
I wasn't able to reproduce your problem with a clean install of version 1.2.3. Have you selected the da,en locales in the `laravellocalization.php`? Did you run `php artisan config:cache` after changes in this file have been made?

Also notice that `localesOrder` are there **ONLY** for the order the locales are displayed in the language selector. This has nothing to do with the default locale at all.

**Comment by sarotnem** [comment] 2017-02-28 14:05
I reproduced your problem and you are right. However notice that localesOrder are there ONLY for the order the locales are displayed in the language selector. This has nothing to do with the default locale at all.

**Comment by RasmusStougaard** [comment] 2017-02-28 20:17
Ahh okay good to know :)

**Comment by yclaes** [comment] 2017-07-19 15:00
+1

**Comment by S4Mi** [comment] 2017-12-02 11:58
Maybe it's because of your browser language and Accept-Language config.

**Comment by S4Mi** [comment] 2017-12-02 11:59
Maybe it's because of your browser language and Accept-Language config.

**Comment by mcamara** [comment] 2017-12-03 11:11
Closing this issue as @sarotnem answer is right.

**Comment by mcamara** [comment] 2017-12-03 11:11
Closing this issue as @sarotnem answer is right.

**Closed by mcamara** 2017-12-03 11:11 UTC

**Comment by RasmusStougaard** [comment] 2017-12-03 12:41
The problem was the fallback locale not working either. Haven't used this package since back then so i assume that part is fixed also
