### ISSUE TITLE
laravel localization using mcamara package giving 404 error on root url but not other urls

### ISSUE THREAD

**Issue by Naveedali1234** [mcamara/laravel-localization#738] opened 2020-08-11 09:35 UTC
i am trying to use mcamara package for language translation but on the root url i am getting 404 error. Actually i am trying to detect the ip address of the user and then set the locale according to that country. i stored the locales and country names in the database. Below is my code:

**AppServiceProvider.php** in this file i am fetching user ip address through https://github.com/stevebauman/location this package and checking the locale from database and set the locale according to that.

        $ip = request()->getClientIp(); 
        $position = Location::get($ip); 
        $locale = Locale::where('country_code',strtolower($position->countryCode))->first();
        if($locale){
            LaravelLocalization::setLocale($locale->country_code);
            
        }

**Web.php**
`Route::group([
'prefix' => LaravelLocalization::getCurrentLocale(),
'middleware' => ['localizationRedirect', 'localeViewPath' ]], function(){
   Route::get('/',function(){
     dd('check');
  }); 
}`

i am getting 404 error on www.example.com but when i do www.example.com/en then it's working fine. Any Help would be really appreciated. i am stuck in it from few days.

**Comment by Mohamed-Farh** [comment] 2021-11-28 15:01
### go to your bootstrap folder **and delete the ( config.php )** **and if there is a file called route in the bootstrap folder delete it too**

**Comment by coder2318** [comment] 2022-04-25 06:37
php artisan route:trans:clear

**Comment by royallife88** [comment] 2022-06-28 14:09
@Naveedali1234 I am also trying the same. But no success. Any solution you found?

**Comment by MohamedAlwhaidi** [comment] 2022-07-16 14:53
Same error

**Comment by muhammadelalfy** [comment] 2023-01-03 09:30
check your RouteServiceProvider if there are prfix assigned to your routes remove it .. if you added a prefix and need it .. move it to routes file it self .. 'prefix' => LaravelLocalization::setLocale()      <= this prefix should be the first prefix

**Comment by ricardofreeman** [comment] 2023-06-07 08:17
In case this will help anyone in the future, routes must not be cached so if you run **php artisan route:cache** or **php artisan optimize** locally or after deploying to the server, you will likely get the 404 in your routes.

**Comment by kevin4dhd** [comment] 2023-11-05 18:11
any solution?

**Comment by AhmedFawzy** [comment] 2024-06-22 18:03
Just follow the guide

https://github.com/mcamara/laravel-localization/blob/master/CACHING.md

**Comment by iwasherefirst2** [comment] 2024-12-06 22:28
> i am trying to use mcamara package for language translation but on the root url i am getting 404 error. Actually i am trying to detect the ip address of the user and then set the locale according to that country. i stored the locales and country names in the database. Below is my code:
> 
> **AppServiceProvider.php** in this file i am fetching user ip address through https://github.com/stevebauman/location this package and checking the locale from database and set the locale according to that.
> 
> ```
>     $ip = request()->getClientIp(); 
>     $position = Location::get($ip); 
>     $locale = Locale::where('country_code',strtolower($position->countryCode))->first();
>     if($locale){
>         LaravelLocalization::setLocale($locale->country_code);
>         
>     }
> ```
> 
> **Web.php** `Route::group([ 'prefix' => LaravelLocalization::getCurrentLocale(), 'middleware' => ['localizationRedirect', 'localeViewPath' ]], function(){ Route::get('/',function(){ dd('check'); }); }`
> 
> i am getting 404 error on [www.example.com](http://www.example.com) but when i do [www.example.com/en](http://www.example.com/en) then it's working fine. Any Help would be really appreciated. i am stuck in it from few days.

The issue is that the locale detected from `$ip` (likely `en`) sets the route prefix to `en` `('prefix' => LaravelLocalization::getCurrentLocale()`), causing `http://www.example.com` to 404 since no route exists without a prefix.

You can fix this by defining a fallback route to redirect to the localized version manually, or use ``'prefix' => LaravelLocalization::setLocale()` .

**Closed by iwasherefirst2** 2024-12-06 22:28 UTC
