### ISSUE TITLE
BUG: urlsIgnored doesn't work in getLocalizedURL and other methods

### ISSUE THREAD

**Issue by uacode** [mcamara/laravel-localization#878] opened 2023-08-06 09:56 UTC
In cfg:
'urlsIgnored' => ['/', '/en'],

But call in tpl
```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <link rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" />
    @endforeach
```

Generated URLs without skip route
```

**<link rel="alternate" hreflang="en" href="http://127.0.0.1:8000/en" />**
<link rel="alternate" hreflang="es" href="http://127.0.0.1:8000/es" />
<link rel="alternate" hreflang="fr" href="http://127.0.0.1:8000/fr" />
...
```

**Comment by Adron55** [comment] 2023-08-07 06:55
In laravellocalization.php there is option hideDefaultLocaleInURL. If your default language is en. It will hide it for you. 
 'hideDefaultLocaleInURL' => true,
I had some problem when translating on language selector. I just checked if it is English. 
{{LaravelLocalization::getURLFromRouteNameTranslated($localeCode, 'routes.index',[],true)}}
I remember getLocalizedURL didn't work correctly so I switched to routes translation in each folder      
'index' => '',

**Comment by iwasherefirst2** [comment] 2024-12-04 21:18
Thank you for reporting this issue. Since it's been more than a year without follow-up and the problem isn't entirely clear, I will go ahead and close this issue. If the problem still persists, please feel free to reopen it with updated information and more details to help us better understand and address the issue.

Thanks for your understanding!

**Closed by iwasherefirst2** 2024-12-04 21:18 UTC
