### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Nuada26** [mcamara/laravel-localization#482] opened 2017-08-23 14:21 UTC
Hi everyone,

I have install laravel localization by mcamara, so i followed getting started, so i have put this code on my api.php:

Route::group(['prefix' => LaravelLocalization::setLocale(),
], function () {

    Route::get('/accelerometerref', 'AccelerometerRefController@get');
});
when i use this adress :

http://127.0.0.1/laravel/public/api/accelerometerref

it's works but when i add the local in URL like that :

http://127.0.0.1/laravel/public/api/es/accelerometerref

it's not works and say :

Sorry, the page you are looking for could not be found.

what am i doing wrong ? If any one can help me.

**Comment by leMaur** [comment] 2017-09-11 12:00
Have you added the middleware in your route group?
Look the installation guide here: https://github.com/mcamara/laravel-localization#middleware

Let me know if this helps..

**Comment by Nuada26** [comment] 2017-09-13 08:18
I have did that , but route not exist.

**Comment by PatrikValkovic** [comment] 2017-09-17 15:31
I had same issue and I finally realize that language parameter must be first in URL. So instead of `http://127.0.0.1/laravel/public/api/es/accelerometerref` you need `http://127.0.0.1/es/laravel/public/api/accelerometerref`. That also mean, that group with `LaravelLocalization::setLocale()` must be the outer one.

**Comment by Nuada26** [comment] 2017-09-18 08:20
it's not works.

**Comment by ctf0** [comment] 2017-11-07 06:37
this is an old issue, atm the middleware add the locale as the first segment, so whatever solution u'll come up with u'll always get the focken not found error.

**Comment by flofloflo** [comment] 2018-01-28 20:26
I've had the same problem with the api routing and fixed it with the following workaround:

First create a class which extends `LaravelLocalization` and override the `setLocale` function:
    
    <?php
    namespace App\Localization;

    use Mcamara\LaravelLocalization\LaravelLocalization as McamaraLocalization;

    class LaravelLocalization extends McamaraLocalization
    {
        public function setLocale($locale = null, int $segment = 1)
        {
            if (empty($locale) || !is_string($locale)) {
                $locale = $this->request->segment($segment);
            }
            return parent::setLocale($locale);
        }
    }
 
Register the new class in the `register()` function of the `AppServiceProvider`: 

    $this->app->alias(LaravelLocalization::class, 'laravellocalization');

Now you can define the segment of the locale in the routing config:

    Route::group(['prefix' => LaravelLocalization::setLocale(null, 2)], function () {
     /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    });

**Comment by johnef** [comment] 2018-04-21 13:32
@flofloflo I try your solution but

Here is my class

```
<?php
namespace App\Models;

use Mcamara\LaravelLocalization\LaravelLocalization as McamaraLocalization;

class LaravelLocalization extends McamaraLocalization
{
	public function setLocale($locale = null, int $segment = 1)
	{
		if (empty($locale) || !is_string($locale)) {
			$locale = $this->request->segment($segment);
		}
		return parent::setLocale($locale);
	}
}
```

`int $segment = 1` Undefined class int and Default value for parameters with a class type can only be NUL.

and I still getting 404 not found

**Comment by flofloflo** [comment] 2018-04-23 07:49
@johnef Are you using PHP 7.0 or higher?

**Comment by johnef** [comment] 2018-04-29 08:13
@flofloflo Thanks for replaying here, but what should the code looks like if I removed this part `public function setLocale($locale = null, $segment = 1)` it will be just the class?
please give a full code after removing the mention.

**Comment by flofloflo** [comment] 2018-04-30 07:26
```php
<?php

namespace App\Localization;

use Mcamara\LaravelLocalization\LaravelLocalization as McamaraLocalization;

class LaravelLocalization extends McamaraLocalization
{
    public function setLocale($locale = null, $segment = 1)
    {
        if (empty($locale) || !is_string($locale)) {
            $locale = $this->request->segment($segment);
        }
        return parent::setLocale($locale);
    }
}
```

**Comment by iwasherefirst2** [comment] 2019-10-28 11:38
Closing this as its a duplicate of #382

**Closed by iwasherefirst2** 2019-10-28 11:38 UTC
