### ISSUE TITLE
Wrong url from LaravelLocalization::getLocalizedURL() if baseUrl exists

### ISSUE THREAD

**Issue by ose1955** [mcamara/laravel-localization#301] opened 2016-03-03 19:30 UTC
**Laravel 5.2.**
I have URL: `http://localhost/foo/en/login`. 
Its base path is `/foo`:

```
$base_path = $this->request->getBaseUrl(); 
// $base_path = '/foo';
```

When I try to create URL:

```
$url = LaravelLocalization::getLocalizedURL(null,'/login');
// $url = 'http://localhost/foo/foo/en/login';
```

Function returns URL with doubled base path.

Just to illustrate the source of the issue:
File `/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php` row 247:

```
$base_path = '';  // Original is:   $base_path = $this->request->getBaseUrl();
```

All works fine after that.

Please fix.

**Comment by kusmierz** [comment] 2016-04-26 09:05
+1

**Comment by GarryOne** [comment] 2016-07-18 11:26
+1

**Comment by iwasherefirst2** [comment] 2019-10-19 23:21
This package has no prefix support. There are all kind of errors when your route looks like this:  http://localhost/foo/en/login`. Redirect Middleware, Cache, Localization will not work correctly. Closing this as  a sub-duplicate of #382

**Closed by iwasherefirst2** 2019-10-19 23:21 UTC
