### ISSUE TITLE
Routes with dynamic parameters

### ISSUE THREAD

**Issue by dily86** [mcamara/laravel-localization#535] opened 2018-03-20 16:03 UTC
Hi,
How could I translate routes with dynamic parameters ?
For example : 
https://mon-site/en/page/my-title
https://mon-site/fr/page/mon-titre
https://mon-site/es/page/mi-titulo

Thanks in advance.

**Comment by user0017** [comment] 2018-03-27 09:10
I think that you have to define translated column on your `post` table
`title_en, title_fr, title_es`  (it recommanded to use separete table like `translated_post_table` )

and use function that deteced the localization on` index()`  for ex to get the tanslated params ,  such as `title , body`.

and for common words,pragraphs is already defined on your `/lang/es.json` file or `/lang/es/something.php`

**Comment by iwasherefirst2** [comment] 2019-10-27 08:26
Closing as this is a duplicate of #502

**Closed by iwasherefirst2** 2019-10-27 08:26 UTC
