### ISSUE TITLE
Some of my routes doesn't want to be translated

### ISSUE THREAD

**Issue by perffy** [mcamara/laravel-localization#377] opened 2016-11-29 14:08 UTC
Hi guys,

i have very strange situation. I have translated my routes as described in the documentation. Everything was fine till one moment in which i observed that some of my routes are no translated.

On my website i have a flag for each translation to change the language. By hover on the flags, it changes only the language, but does not translate the route. The strange thing, is that for some routes it works, but for some not.

For example i have one controller for displaying sport predictions. Here are the routes:

`Route::get(LaravelLocalization::transRoute('routes.prognoses').'.html', ['as' => 'prognoses.index', 'uses' => 'PrognosesController@index']);
`

```
Route::get('{sport}-'.LaravelLocalization::transRoute('routes.prognoses').'/{date}.html', ['as' => 'prognoses.sport_date', 'uses' => 'PrognosesController@index'])->where(['sport' => '[a-z]+', 'date' => '[0-9]{4}-[0-9]{1,}-[0-9]{1,}']);
```

`Route::get(LaravelLocalization::transRoute('routes.prognose').'/{id}/{slug}.html', ['as' => 'prognoses.show', 'uses' => 'PrognosesController@show']);`

Here it fails to translate the routes ?

**Comment by ctf0** [comment] 2017-01-04 00:06
a couple of small edits
1. use the syntax formatting feature in md for better demonstrating of the code
2. for the route pattern u can instead use https://laravel.com/docs/5.3/routing#parameters-global-constraints
3. for the failed translation, can u give more info so we can re-produce

**Comment by subdesign** [comment] 2018-03-14 15:49
same here

**Comment by iwasherefirst2** [comment] 2019-10-20 10:54
Closing this as it is not clear what the issue is and how to reproduce it.

**Closed by iwasherefirst2** 2019-10-20 10:54 UTC
