### ISSUE TITLE
Slug only gets translated if transRoute is used.

### ISSUE THREAD

**Issue by Krypto89** [mcamara/laravel-localization#815] opened 2022-02-03 21:44 UTC
**Describe the bug**
Slug is not translated if transRoute is not used, although those are different features.

**To Reproduce**
If you do not used transRoute but translated slugs
**substituteAttributesInRoute($attributes, $route, $locale);**
gets never called and therefore the slug doesn't get translated.

If transRoute is used in combination with translated slugs
**$this->substituteAttributesInRoute($attributes, $route, $locale);**
get's called and therefore it's working.

This is the call which handles translated slugs:
https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L383

**Comment by iwasherefirst2** [comment] 2024-12-18 20:53
I believe the code has changed, and `transRoute` no longer calls `substituteAttributesInRoute`. In any case, it’s a known issue with translated slugs. I’m closing this as a duplicate of https://github.com/mcamara/laravel-localization/issues/718.

**Closed by iwasherefirst2** 2024-12-18 20:53 UTC
