### ISSUE TITLE
Validation messages not getting translated?

### ISSUE THREAD

**Issue by CristianEstiber** [mcamara/laravel-localization#660] opened 2019-10-03 13:21 UTC
Hi, I only can see my default language translated from validation.php, I change locale and it still getting the wrong validation file, and yes the locale of the app is being swaped because texts, routes etc changes to the target locale.

Saw this same error searching: https://github.com/mcamara/laravel-localization/issues/203, https://github.com/mcamara/laravel-localization/issues/339 but don't understand what they did to make it work, thanks

**Comment by iwasherefirst2** [comment] 2019-10-10 17:06
Can you give an minimal example?

**Comment by iwasherefirst2** [comment] 2019-10-14 21:45
Closing this as its a duplicate of #339

**Closed by iwasherefirst2** 2019-10-14 21:45 UTC
