### ISSUE TITLE
Configurated language not appears

### ISSUE THREAD

**Issue by matteoteknet** [mcamara/laravel-localization#619] opened 2019-02-14 14:50 UTC
Hello,

I successfully installed everything like described in the installation page.
I've in my config/ folder the file "laravellocalization.php" and edited it.
I comment the line about spanish language and uncommented the line about italian language but in mi application the language selector shows english (correct) and spanish (incorrect)

The routes with /es/ works properly and the routes with /it/ not works at all (error 404)

Is there anything I miss in my configuration?
I correctly registered the providers, the route , .. as explained here on git.

Thanks.

**Comment by iwasherefirst2** [comment] 2019-05-05 10:09
Could you show us the content of `routes.php` and `laravellocalization.php`?

**Comment by xlcrr** [comment] 2019-10-10 21:06
@iwasherefirst2 I have the same problem. Been using for months no trouble with /en /es /fr /de /tk /ms but `/it` returns 404

**Comment by xlcrr** [comment] 2019-10-10 21:11
Also, it works fine locally on Homestead but only returns 404 in production

**Comment by iwasherefirst2** [comment] 2019-10-10 21:15
@xlcrr that is a very strange error. Did you enable `it` in `laravellocalization.php` ?

**Comment by xlcrr** [comment] 2019-10-10 22:32
Hi, yes enabled `it` in the config file.

Seen the comments about 1.4.2 bug, will try downgrade and report back

**Comment by xlcrr** [comment] 2019-10-10 23:04
Same error with 1.4.1

**Comment by iwasherefirst2** [comment] 2019-10-10 23:25
@xlcrr hm. Unfortunately I can't really help if I can't reproduce it. I have a fresh installation of Laravel 6 with laravel-localization 1.4.1. If I uncomment `it` in config file and create this minimalistic route:

```
Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect'],
], function () {
    Route::get('/hi', 'WelcomeController@index');
});
```

then `my-example.test/it/hi` works just fine.

If you can reproduce it with a fresh installation, please describe step by step what your doing and post `config/laravellocalization.php` and `web.php` and anything else that you modify for you scenario, aswell the version that you are using.

To the OP

> I comment the line about spanish language and uncommented the line about italian language but in mi application the language selector shows english (correct) and spanish (incorrect)
> 
> The routes with /es/ works properly and the routes with /it/ not works at all (error 404)

Please post at least your complete configuration file `config/laravellocalization.php`. What happens if you dump `supportedLocales` ? It sounds like `es` is enabled and `it` not.

**Comment by xlcrr** [comment] 2019-10-10 23:34
Thanks for the comments @iwasherefirst2 

It's working fine for me locally, even with 1.4.2, but not working in production.

Will test and debug again soon

**Comment by iwasherefirst2** [comment] 2019-10-12 11:29
Since the issue is not reproducible and OP did not response, I will close this issue.

**Closed by iwasherefirst2** 2019-10-12 11:29 UTC
