### ISSUE TITLE
getLocalizedURL broken in Laravel 5

### ISSUE THREAD

**Issue by oriceon** [mcamara/laravel-localization#171] opened 2015-02-09 15:51 UTC
When you use routes with parameters, routes are not anymore translated.

From language selector, in register page:

{!! link_to(LaravelLocalization::getLocalizedURL($localeCode), $properties['native'], ['rel' => 'alternate', 'hreflang' => $localeCode]) !!}

en
**'register' => 'account/register/{code?}',**

ro
**'register' => 'cont/inregistrare/{code?}',**

As i see, problem is caused in Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes, $routeName is empty.

**Comment by mcamara** [comment] 2015-02-10 12:34
Fixed in the latest version 1.0.4

Thanks for your feedback!

**Comment by oriceon** [comment] 2015-02-10 14:09
Thanks for fix but is not working as expected.

i did an echo on fix substituteAttributesInRoute method from getRouteNameFromAPath() and it return cont/inregistrare/**inregistrare** for code parameter  ... 'register' => 'cont/inregistrare/{code?}', 

expected to return only **cont/inregistrare** if i don`t have code parameter in url

**Comment by jaumesala** [comment] 2015-02-10 15:30
I agree. last update `1.0.4` doesn't fix the *parameters bug*. You can reproduce the problem with the next setup:

 
```PHP
//config/laravelLocalization.php
'supportedLocales' => array(
   'ca', //...
   'es', //...
   'en', //...
),
'useAcceptLanguageHeader' => false,
'useSessionLocale' => false,
'useCookieLocale' => false,
'hideDefaultLocaleInURL' => true,

// lang/en/routes.php
<?php
   return array(
      "home"         => "/",
      "products"	 => "products/{ref}"
);

// inside.a.view.blade.php
{{ LaravelLocalization::getURLFromRouteNameTranslated(Config::get('app.locale'), 'routes.products') }}
```

I should get `http://example.com/products/` but I get `http://example.com/products/{ref}`.
And the same for other languages...

There's also a problem with the **home** route. With the same configuration, if I call
```PHP
{{ LaravelLocalization::getURLFromRouteNameTranslated(Config::get('app.locale'), 'routes.home') }}
```
 I get `//` instead of `http://example.com/`

I haven't had time to digg into the code, sorry :-/

**Comment by jaumesala** [comment] 2015-02-10 17:01
I've just find out that `getURLFromRouteNameTranslated()` works as expected if the route has optional parameters (the ones with "?").
Maybe there's something wrong with the method `substituteAttributesInRoute()` @mcamara?

**Comment by mcamara** [comment] 2015-02-10 17:54
It's weird, I have tested with dozens of routes and they work, I will test it deeplier.

Anyway, @jaumesala , your example is not valid, ref is mandatory so it's normal that the system leave it as {ref} in the final url if you don't provide the 'ref' value in the third attribute of the getURLFromRouteNameTranslated function.

Thanks for the feedback, I would try to sort this out asap!

**Comment by jaumesala** [comment] 2015-02-11 10:27
But @mcamara , there are two type of routes in the system, the ones that resolve a route and the ones exposed in the view. Let me explain:

Given the next translation routes:
```PHP
//resources/lang/en/routes.php
"home"       => "/",
"products"   => "products/{slug}",
"news"       => "news/{slug?}",
```
With the following routes:
```PHP
//app/Http/routes.php
Route::get(LaravelLocalization::transRoute('routes.home'),[ 'as' => 'home', function(){
   return View::make('sections.home.index');
}]);
Route::get(LaravelLocalization::transRoute('routes.products'),[ 'as' => 'products', function($slug){
   return View::make('sections.products.index');
}]);
Route::get(LaravelLocalization::transRoute('routes.news'),[ 'as' => 'news', function($slug = null){
   return View::make('sections.news.index');
}]);
``` 
The method `LaravelLocalization::transRoute()` should return the following strings:
```PHP
"/"
"products/{slug}"
"news/{slug?}"
```

But, in a blade view, if we have this:
```PHP
LaravelLocalization::getURLFromRouteNameTranslated(Config::get('app.locale'), 'routes.home')
LaravelLocalization::getURLFromRouteNameTranslated(Config::get('app.locale'), 'routes.products')
LaravelLocalization::getURLFromRouteNameTranslated(Config::get('app.locale'), 'routes.news')
```
The method `LaravelLocalization::getURLFromRouteNameTranslated()` should return the following strings (no attributes passed as third argument):
```PHP
"http://domain.dev/"
"http://domain.dev/products/"
"http://domain.dev/news/"
```

From my point of view, Laravel should be the one responsable to generate an exception if we call a route that requires a mandatory attribute and we haven't provided it. 

Right now the package, given the previous examples, generates this (in a view file): 
```PHP
"//"
"http://domain.dev/products/{slug}"
"http://domain.dev/news/"
```

OMG, what a long comment! Hope it will help you. Otherwise let me know it, I'm open to help you.
Salut! :-)

**Comment by oriceon** [comment] 2015-02-12 14:48
I confirm now that my issue has been fixed in last version. Thanks!

**Comment by mcamara** [comment] 2015-02-12 14:49
If you ask for a route without needed parameters Laravel doesn't raise any exception, it just leave the attribute between brackets as the package. 

I don't know what to do, should I raise an exception when an attribute is needed or should I just print the attribute between brackets as now?

**Comment by jaumesala** [comment] 2015-02-12 20:15
@mcamara I don't understand what you mean with:
> If you ask for a route without needed parameters using route function Laravel doesn't raise any exception, it just leave the attribute between brackets as the package.

What I meant with my previous comment is that, **in a view** when you want to generate a **URL** for an specific route,  `LaravelLocalization::getURLFromRouteNameTranslated()` should **only return** the **fixed part** specified in the translation route's file (resources/lang/XX/routes.php). So, i.e.:

```PHP
//config/app.php
'locale' => 'en',

//config/laravelLocalization.php
'supportedLocales' => [
   'ca', //...
   'en', //...
],
'useAcceptLanguageHeader' => false,
'useSessionLocale' => false,
'useCookieLocale' => false,
'hideDefaultLocaleInURL' => true,

//resources/lang/en/routes.php
return [
   'home'       =>  '/',
   'products'   => 'products/{slug}',
   'news'       => 'news/{slug?}',
   'lorem'      => 'lorem/{ipsum}/{dolor?}'
];

//resources/lang/en/routes.php
return [
   'home'       =>  '/',
   'products'   => 'productes/{slug}',
   'news'       => 'noticies/{slug?}',
   'lorem'      => 'lorem/{ipsum}/{dolor?}'
];

//app/Http/routes.php
Route::get(LaravelLocalization::transRoute('routes.home'),[ 'as' => 'home', function(){
   return View::make('home.index');
}]);
Route::get(LaravelLocalization::transRoute('routes.products'),[ 'as' => 'products', function($slug){
   return View::make('products.index');
}]);
Route::get(LaravelLocalization::transRoute('routes.news'),[ 'as' => 'news', function($slug = null){
   return View::make('news.index');
}]);
Route::get(LaravelLocalization::transRoute('routes.lorem'),[ 'as' => 'lorem', function($ipsum, $dolor = null){
   return View::make('lorem.index');
}]);
```
The routes generated by the method `LaravelLocalization::getURLFromRouteNameTranslated()` (inside a view, of course) should be:
```
//without arguments
// Routes en
Home       => http://example.dev/
Products   => http://example.dev/products/
News       => http://example.dev/news/
Lorem      => http://example.dev/lorem/

// Routes ca
Home       => http://example.dev/
Products   => http://example.dev/ca/productes/
News       => http://example.dev/ca/noticies/
Lorem      => http://example.dev/ca/lorem/
```
Pay attention to route "lorem", it expects 2 arguments, one of them mandatory, but nothing is printed!
Now, if we call again the method `LaravelLocalization::getURLFromRouteNameTranslated()` but this time we supply the needed route arguments, we should get the complete routes, like so:
```
//with arguments
// Routes en
Home       => http://example.dev/
Products   => http://example.dev/products/laravel-localization
News       => http://example.dev/news/mcamara-rules
Lorem      => http://example.dev/lorem/foo/bar

// Routes ca
Home       => http://example.dev/
Products   => http://example.dev/ca/productes/laravel-localization
News       => http://example.dev/ca/noticies/mcamara-mola
Lorem      => http://example.dev/ca/lorem/foo/bar
```
So, with your question, should you raise an exception if no arguments are passes, IMHO, absolutely no! Why? Because the rendered (HTML) view doesn't care about what's inside, you could even hard-code a link to a route (in a view) and make a mistake... Then, if you click the link, well, Laravel will throw a NotFoundHttpException exception.

If you still have any question let me know it!

Damn, I should use the time spent writing the bug reviews in fixing the bugs indeed ^^'

**Comment by ntopulos** [comment] 2015-03-30 22:06
I confirm that `getLocalizedURL()` does not work as it should.

I am trying to generate a [sitemap](https://support.google.com/webmasters/answer/2620865?hl=en), and I get very strange results: third of my routes are translated but not the rest of them, and I see no correlation with anything that could explain this behavior.
All considered routes work just fine elsewhere with the `action()`-`transRoute()` couple.

**Comment by woltbit** [comment] 2015-06-12 05:58
hi @mcamara is this working for laravel 5.1.* ?? thanks in advance

**Closed** 2015-12-28 10:01 UTC
