### ISSUE TITLE
404 not found after route:trans:cache

### ISSUE THREAD

**Issue by asterism612** [mcamara/laravel-localization#736] opened 2020-07-31 07:13 UTC

**Comment by marijoo** [comment] 2020-08-05 11:05
This happens with `php artisan optimize`, `php artisan route:cache` as well as with `php artisan route:trans:cache`. After clearing the cache with `php artisan cache:clear` routes work again.

**Comment by iwasherefirst2** [comment] 2020-08-05 16:25
Is it releated to #712? Please show your route file.

**Comment by iwasherefirst2** [comment] 2020-08-10 11:23
Closing this as a duplicate of #712

**Comment by marijoo** [comment] 2020-09-11 17:30
@iwasherefirst2 I created a minimal setup on a fresh Laravel 7 installation and put it in a repo. You can find the commit here:
https://github.com/marijoo/laravel-localization-route-cache/commit/90924fba385ab8e5074ab95a3a1c96f6d6863f36

As you can see this is a minimal setup but the problem occurs as described above:

> This happens with `php artisan optimize`, `php artisan route:cache` as well as with `php artisan route:trans:cache`. After clearing the cache with `php artisan cache:clear` routes work again.

Can you reopen this issue, please? If I can further help, please don't hesitate.

**Comment by iwasherefirst2** [comment] 2020-10-25 17:46
Fixed with https://github.com/mcamara/laravel-localization/commit/0ec9e75c551ce9e5fa094e4c8034bdad13c59b3b

**Closed by iwasherefirst2** 2020-10-25 17:46 UTC
