### ISSUE TITLE
Resource routes not found anymore after implementing this package

### ISSUE THREAD

**Issue by renege** [mcamara/laravel-localization#260] opened 2015-11-19 09:53 UTC
Why do I get an error after implementing your package @mcamara ?:

`ErrorException in UrlGenerator.php line 296:
Route [cars.create] not defined.`

In aliasses config i have: `'Localize'  => Mcamara\LaravelLocalization\Facades\LaravelLocalization::class`

And this route worked fine before.

```
Route::group(['namespace' => 'Foobar',
 'middleware' => ['auth', 'localeSessionRedirect', 'localizationRedirect'],
 'prefix' => Localize::setLocale()], function()
{
    resource('cars', 'CarsController');
});
```

**Comment by PMK** [comment] 2015-11-23 18:21
And if you do `resource('routes.cars', 'CarsController');`?

**Comment by arcanedev-maroc** [comment] 2015-11-23 21:10
This is caused by `Route::group()` + `resource()`, you can not access `cars.create` route name because it's add the prefix from the group.

Check this: https://github.com/illuminate/routing/blob/master/ResourceRegistrar.php#L212

This is how i fix it in my Localization package: https://github.com/ARCANEDEV/Localization/issues/9

**Comment by loranger** [comment] 2016-02-26 10:35
Is there a __simple__ way to use this package with route names without editing Illuminate methods ?

**Comment by loranger** [comment] 2016-03-03 17:09
Any clue @mcamara ?

**Comment by iwasherefirst2** [comment] 2019-10-19 23:07
Closing this as the OP question seems to be solved

**Closed by iwasherefirst2** 2019-10-19 23:07 UTC
